/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module iv.sdl2.image /*is aliced*/;
pragma(lib, "SDL2_image");

import iv.sdl2.sdl;

alias IMG_SetError = SDL_SetError;
alias IMG_GetError = SDL_GetError;

enum : ubyte {
  SDL_IMAGE_MAJOR_VERSION = 2,
  SDL_IMAGE_MINOR_VERSION = 0,
  SDL_IMAGE_PATCHLEVEL    = 0,
}

void SDL_IMAGE_VERSION() (ref SDL_version x) {
  x.major = SDL_IMAGE_MAJOR_VERSION;
  x.minor = SDL_IMAGE_MINOR_VERSION;
  x.patch = SDL_IMAGE_PATCHLEVEL;
}

enum {
  IMG_INIT_JPG  = 0x00000001,
  IMG_INIT_PNG  = 0x00000002,
  IMG_INIT_TIF  = 0x00000004,
  IMG_INIT_WEBP = 0x00000008,
}

extern(C) @nogc nothrow {
  int IMG_Init (int);
  int IMG_Quit ();
  const(SDL_version)* IMG_Linked_Version ();
  SDL_Surface* IMG_LoadTyped_RW (SDL_RWops*, int, const(char)*);
  SDL_Surface* IMG_Load (const( char )*);
  SDL_Surface* IMG_Load_RW (SDL_RWops*, int);

  SDL_Texture* IMG_LoadTexture (SDL_Renderer*, const(char)*);
  SDL_Texture* IMG_LoadTexture_RW (SDL_Renderer*, SDL_RWops*, int);
  SDL_Texture* IMG_LoadTextureTyped_RW (SDL_Renderer*, SDL_RWops*, int, const(char)*);

  int IMG_isICO (SDL_RWops*);
  int IMG_isCUR (SDL_RWops*);
  int IMG_isBMP (SDL_RWops*);
  int IMG_isGIF (SDL_RWops*);
  int IMG_isJPG (SDL_RWops*);
  int IMG_isLBM (SDL_RWops*);
  int IMG_isPCX (SDL_RWops*);
  int IMG_isPNG (SDL_RWops*);
  int IMG_isPNM (SDL_RWops*);
  int IMG_isTIF (SDL_RWops*);
  int IMG_isXCF (SDL_RWops*);
  int IMG_isXPM (SDL_RWops*);
  int IMG_isXV (SDL_RWops*);
  int IMG_isWEBP (SDL_RWops*);

  SDL_Surface* IMG_LoadICO_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadCUR_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadBMP_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadGIF_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadJPG_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadLBM_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadPCX_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadPNG_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadPNM_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadTGA_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadTIF_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadXCF_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadXPM_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadXV_RW (SDL_RWops*);
  SDL_Surface* IMG_LoadWEBP_RW (SDL_RWops*);

  SDL_Surface* IMG_ReadXPMFromArray (char**);

  int IMG_SavePNG (SDL_Surface*, const(char)*);
  int IMG_SavePNG_RW (SDL_Surface*, SDL_RWops*, int);
}
